services:
  backend:
    image: barmaglot92/media-backend:latest
    restart: on-failure
    volumes:
      - /movies:/app/workDir/data
    expose:
      - 3000

  frontend:
    image: barmaglot92/media-frontend:latest
    restart: on-failure
    volumes:
      - /movies:/app/public
    links:
      - "backend"
    ports:
      - "80:80"