services:
  backend:
    image: barmaglot92/media-backend:latest
    restart: on-failure
    volumes:
      - ./movies:/app/workDir/data
    expose:
      - 3000

  frontend:
    image: barmaglot92/media-frontend:latest
    restart: on-failure
    network_mode: host
    links:
      - "backend"
    expose:
      - 80